apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: "nginx" # toto je nejdulezitejsi jelikoz jsme nainstalovali IngressClass tak se potrbujeme na tento class odkazat
  name: ingress-resource-1
spec:
  rules:
  - host: nginx.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx-deploy-main
            port: 
              number: 80
  # Update resp pridani dalsiho dns zaznamu
  # - host: new.nginx.example.com
  #   http:
  #     paths:
  #     - path: /
  #       pathType: Prefix
  #       backend:
  #         service:
  #           name: nginx-deploy-main2
  #           port: 
  #             number: 80            
